#-------------------------------
# General Site Settings
title: Ying
logo: logo.svg # You can add own logo.
description: Adversarial Machine Learning, Software Testing


#-------------------------------
# Author Settings
author:
  name: Ying Meng
  image: 01.jpg
  say-hello: Hello world
  bio: 


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: meng # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

